version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/plugin"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/converter"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
